jobs:
  include:
  - stage: backend
    language: java
    script: cd backend; ./gradlew build; ls -al;

    before_deploy:
    - echo TRAVIS_TAG is $TRAVIS_TAG
    - echo TRAVIS_REPO_SLUG is $TRAVIS_REPO_SLUG
    - echo the name of the jar is $(basename $(ls build/libs/*.jar))
    - ../ci-scripts/travis-update-jar-filename.sh $(basename $(ls build/libs/*.jar))

    deploy:
      provider: releases
      tag_name: $TRAVIS_TAG
      target_commitish: $TRAVIS_COMMIT
      name: $TRAVIS_TAG
      api_key:
        secure: 0U2zTo+mVLy4MuhrGnmAfTVPDrH8nQibYAjqWB/uVKSMPZLfWc6gxPqzwlMj6d2/vDNDZHQtNtJuVz77sa4gp3W/39FnmsnuCesiM9fBvlJIxL8thpvUCk3QIbbBjurcksaeC7rXTKjEMiU2qpT8mSfOUBzaC7vLS64swrNADLJJyeAhXNG5NACYDY40j6BlWy9yMMmRIr5EUAlUo3nLLssfdtneXJus06Q3dy2Nnvnvy6GwkC87ZHvuPabV0QtxnHaKXnQqr+aqktaHRAb7L3Qv1pm4FbOsLBNx6nTVLn2ZB4LHBrhHs5b9EGwwTIglY/zrHSqck/copMplTtPXndikf1lOPHW1YdjMSNHcm30MdlMtUI38rrzHEuUHgWOkTRo3z2n25Qgw0nf2XWh1j2NZSSOFrlp6kLH6zOM9Y0QVNdzdUSflfGt5AfNr6uZm2fszjo4EU+KHkpkXCzzZKf4g832SpeLei+DMRKL3jpPSnqgdCRwnsRkYlfUlnfZvY5sysFYi0H+LviM8QT//dr+aAuqxIiucAXlj/jNfCDLgYqG++PyoHTIDRWXNVXILAzDprtyhHBFxVVlefhr8qucyEjZ9ZWjTn7sDbNBqDQ/rt+eHI3wqrjvIriTqJVe22VOYpDuoZQX/Th0SCxo8HP+ywq7eaSPybFt8PbBAye4= 
      file_glob: true
      file: ./**/*.jar
      skip_cleanup: true
      on:
        all_branches: true
        tags: true

  - stage: ios
    language: objective-c
    xcode_project: ios/Stickies.xcodeproj
    xcode_scheme: Stickies
    xcode_destination: platform=iOS Simulator,OS=11.4,name=iPhone X
    before_script: 

    after_script: 
      - echo TRAVIS_TAG is $TRAVIS_TAG
      - echo CHECKING if we have the BACKEND_JAR_FILENAME... $BACKEND_JAR_FILENAME
      - echo the URL is... "https://github.com/$TRAVIS_REPO_SLUG/releases/download/$TRAVIS_TAG/$BACKEND_JAR_FILENAME"
      - curl -L "https://github.com/$TRAVIS_REPO_SLUG/releases/download/$TRAVIS_TAG/$BACKEND_JAR_FILENAME" > backend.jar ;  
      - java -jar backend.jar&
      - echo going to sleep to wait for backend.jar to start up; sleep 30; 
      - curl localhost:8080/
      
